import {
  Coffee,
  Compass,
  Crown,
  Drama,
  Heart,
  LandPlot,
  Laugh,
  MicVocal,
  Orbit,
  Search,
  Shield,
  Skull,
  Sparkles,
  Swords,
  Trophy,
  WandSparkles,
} from "lucide-react";

export const GENRES = [
  { label: "Action", value: "action", icon: Swords },
  { label: "Adventure", value: "adventure", icon: Compass },
  { label: "Comedy", value: "comedy", icon: Laugh },
  { label: "Drama", value: "drama", icon: Drama },
  { label: "Fantasy", value: "fantasy", icon: WandSparkles },
  { label: "Romance", value: "romance", icon: Heart },
  { label: "Sci-Fi", value: "sci-fi", icon: Orbit },
  { label: "Slice of Life", value: "slice-of-life", icon: Coffee },
  { label: "Mystery", value: "mystery", icon: Search },
  { label: "Horror", value: "horror", icon: Skull },
  { label: "Sports", value: "sports", icon: Trophy },
  { label: "Supernatural", value: "supernatural", icon: MicVocal },
  { label: "School", value: "school", icon: LandPlot },
  { label: "Magic", value: "magic", icon: Sparkles },
  { label: "Military", value: "military", icon: Shield },
  { label: "Shounen", value: "shounen", icon: Crown },
].filter((genre) => genre.label && genre.value && genre.icon);
